server:
  port: 6001
  
spring:
  application:
    name: yjlc-rest-consumer
    
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
instance:
    preferIpAddress: true